In [1]:
import pandas as pd

In [2]:
pd.read_csv('app/geo/Data/geo_banks.csv')

,Unnamed: 0,banque,lat,long,geometry,index_right,delegation,OBJECTID,C_DELEG,LABEL,C_SECT,LABEL_AR,municipalite,circonscription,gouvernorat,CODE_GOUV,Shape__Area,Shape__Length
0,0,abc,36.836275,10.227907,POINT (10.2279069 36.8362745),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
1,9,abc,36.847116,10.198290,POINT (10.1982902 36.8471161),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
2,16,abc,36.836275,10.227907,POINT (10.2279069 36.8362745),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
3,18,amen,36.821501,10.189833,POINT (10.189833 36.821501),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
4,21,amen,36.817084,10.187658,POINT (10.187658 36.817084),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1866,1859,biat,34.737968,10.092778,POINT (10.09277820587158 34.73796844482422),20,Bir ali Ben Kelifa,1331,3463,BIR ALI BEN KHELIFA,346351,بئر علي بن خليفة,Bir Ali Ben Khelifa,Sfax_1,Sfax,34,0.001178,0.177338
1867,1565,zitouna,36.836450,9.941088,POINT (9.941088000000001 36.83645),46,Djedeida,318,1456,DJEDAIDA,145651,الجديدة,Djedaida,Manouba,Manouba,14,0.000981,0.256059
1868,1677,biat,37.036900,10.040097,POINT (10.0400972366333 37.03689956665039),257,Utique,559,1760,UTIQUE,176051,أوتيك,Utique,Bizerte,Bizerte,17,0.005445,0.334651
1869,1685,biat,36.899181,10.121834,POINT (10.12183380126953 36.8991813659668),132,Kalaât El Andalous,187,1254,KALAAT EL ANDALOUS EST,125451,قلعة الاندلس الشرقية,Kalaat El Andalous,Ariana,Ariana,12,0.006108,0.608100
1870,1708,biat,35.956631,10.470147,POINT (10.47014713287354 35.95663070678711),220,Sidi Bou Ali,991,3158,SIDI BOU ALI,315851,سيدي بوعلي,Sidi Bou Ali,Sousse,Sousse,31,0.002096,0.255110

In [3]:
pop = pd.read_csv('app/geo/Data/population.csv', delimiter=';', skiprows=6)

In [4]:
pop = pop.rename(columns={'Unnamed: 0': 'Gouvernorat'})

In [5]:
pop

,Gouvernorat,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Tunisie,10895219,11012486,11158628,11292778,11418219,11532078,11638066,11726178,11783722
1,Gouvernorat de Tunis,1051199,1057782,1063180,1065858,1068095,1069579,1071244,1073249,1075015
2,Gouvernorat de L'Ariana,560772,579260,595769,611885,627141,641433,654315,662694,667354
3,Gouvernorat de Ben Arous,619728,634594,648978,663083,676781,689954,701984,710502,715490
4,Gouvernorat de Manouba,375774,380951,388200,395069,402164,409416,415907,420445,423111
5,Gouvernorat de Nabeul,779764,790694,804551,817502,829962,841806,852668,861260,866838
6,Gouvernorat de Zaghouan,175676,177434,179804,181947,183988,185897,187663,189176,190127
7,Gouvernorat de Bizerte,564941,569541,575449,580241,584594,588354,591937,595240,597490
8,Gouvernorat de Bèja,304027,303446,304844,305454,306005,306398,306782,307507,308148
9,Gouvernorat de Jendouba,404240,401903,403123,403316,403407,403253,403344,404100,404738
10,Gouvernorat du Kef,245542,243581,245054,245748,246149,246189,246313,246820,247289
11,Gouvernorat de Siliana,224898,223395,224788,225939,226665,226883,227198,227992,228691
12,Gouvernorat de Sousse,662487,677501,690464,702917,714694,725647,735746,743278,747887
13,Gouvernorat de Monastir,540097,550791,560875,570593,579908,588694,596693,602659,606401
14,Gouvernorat de Mahdia,408318,412019,418281,424380,429839,434566,439059,443075,445704
15,Gouvernorat de Sfax,947051,958113,970931,982251,992812,1002358,1011259,1018373,1022900
16,Gouvernorat de Kairouan,569454,571296,575733,580680,585001,588493,591901,596221,599560
17,Gouvernorat de Kasserine,437493,440061,444113,447869,451338,454430,457353,460820,463497
18,Gouvernorat de Sidi Bouzid,427318,430899,435905,440665,444825,448273,451612,455062,457537
19,Gouvernorat de Gabès,371848,375333,380630,385723,390569,395091,399264,402691,404829
20,Gouvernorat de Medenine,475670,480921,488012,494741,501056,506822,512164,516385,519074
21,Gouvernorat de Tataouine,149210,149537,149859,150065,150312,150508,150770,151323,151750
22,Gouvernorat de Gafsa,336763,337921,341019,344075,346715,348799,350826,352809,354169
23,Gouvernorat de Tozeur,107067,108188,109593,110930,112162,113254,114275,115119,115675
24,Gouvernorat de Kébili,155883,157322,159473,161849,164038,165981,167790,169378,170450

In [6]:
df_pop = pd.melt(pop, id_vars=['Gouvernorat'], value_vars=pop.columns[1:])

In [7]:
df_pop = df_pop.rename(columns={'variable': 'year', 'value': 'population'})

In [30]:
import plotly.express as px
import geopandas as gpd

In [13]:
geometries = gpd.read_file('app/geo/Data/TUN_adm1.shp')
df = pd.read_csv('app/geo/Data/geo_banks.csv')

In [26]:
gov_map = {
 'Ben Arous (Tunis Sud)': 'Ben Arous',
 'Béja': 'Beja',
 'Gabès': 'Gabes',
 'Kassérine': 'Kasserine',
 'Kebili': 'Kebeli',
 'Manubah': 'Manouba',
 'Médenine': 'Mednine',
 'Sidi Bou Zid': 'Sidi Bouzid',
}

In [32]:
#geometries.NAME_1 = geometries.NAME_1.apply(lambda x : gov_map[x] if x in gov_map else x)

In [38]:
geometries.head()

,ID_0,ISO,NAME_0,ID_1,NAME_1,VARNAME_1,NL_NAME_1,HASC_1,CC_1,TYPE_1,ENGTYPE_1,VALIDFR_1,VALIDTO_1,REMARKS_1,Shape_Leng,Shape_Area,geometry
0,225,TUN,Tunisia,2955,Manouba,NaN,NaN,TN.MN,NaN,Wilayat,Governorate,200009,Present,NaN,1.747941,0.102080,"POLYGON ((9.82699 36.96883, 9.83085 36.96881, ..."
1,225,TUN,Tunisia,2956,Mednine,Madaniyin|Madanin|Medenin,NaN,TN.ME,NaN,Wilayat,Governorate,1981,Present,NaN,12.475052,0.836014,"MULTIPOLYGON (((11.45264 33.17486, 11.45264 33..."
2,225,TUN,Tunisia,2957,Monastir,Al Munastir,NaN,TN.MS,NaN,Wilayat,Governorate,19740309,Present,NaN,2.306264,0.098287,"MULTIPOLYGON (((11.02347 35.64375, 11.02347 35..."
3,225,TUN,Tunisia,2958,Nabeul,Cap Bon|Nabil|Nabol|Nabul,NaN,TN.NB,NaN,Wilayat,Governorate,19730524,Present,NaN,3.969903,0.287665,"MULTIPOLYGON (((10.50375 36.73236, 10.50375 36..."
4,225,TUN,Tunisia,2959,Sfax,Safaqis|?afaqis|?faqis,NaN,TN.SF,NaN,Wilayat,Governorate,19740309,Present,NaN,8.180811,0.711881,"MULTIPOLYGON (((10.27681 34.32208, 10.27681 34..."

In [100]:
set(geometries.NAME_1)

{'Ariana',
 'Beja',
 'Ben Arous',
 'Bizerte',
 'Gabes',
 'Gafsa',
 'Jendouba',
 'Kairouan',
 'Kasserine',
 'Kebeli',
 'Le Kef',
 'Mahdia',
 'Manouba',
 'Mednine',
 'Monastir',
 'Nabeul',
 'Sfax',
 'Sidi Bouzid',
 'Siliana',
 'Sousse',
 'Tataouine',
 'Tozeur',
 'Tunis',
 'Zaghouan'}

{'Ariana',
 'Beja',
 'Ben Arous',
 'Bizerte',
 'Gabes',
 'Gafsa',
 'Jendouba',
 'Kairouan',
 'Kasserine',
 'Kebeli',
 'Le Kef',
 'Mahdia',
 'Manouba',
 'Mednine',
 'Monastir',
 'Nabeul',
 'Sfax',
 'Sidi Bouzid',
 'Siliana',
 'Sousse',
 'Tataouine',
 'Tozeur',
 'Tunis',
 'Zaghouan'}

In [35]:
df.head()

,Unnamed: 0,banque,lat,long,geometry,index_right,delegation,OBJECTID,C_DELEG,LABEL,C_SECT,LABEL_AR,municipalite,circonscription,gouvernorat,CODE_GOUV,Shape__Area,Shape__Length
0,0,abc,36.836275,10.227907,POINT (10.2279069 36.8362745),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
1,9,abc,36.847116,10.198290,POINT (10.1982902 36.8471161),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
2,16,abc,36.836275,10.227907,POINT (10.2279069 36.8362745),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
3,18,amen,36.821501,10.189833,POINT (10.189833 36.821501),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961
4,21,amen,36.817084,10.187658,POINT (10.187658 36.817084),38,Cité El Khadhra,63,1159,CITE EL KHADRA,115951,حي الخضراء,Tunis,Tunis_2,Tunis,11,0.000029,0.020961

In [126]:
pov = pd.read_excel('app/geo/Data/poverty_rate.xlsx', decimal=',')

In [127]:
pov.columns

Index(['Gouvernorat:', 'Unnamed: 1', 'Taux de pauvreté'], dtype='object')

In [128]:
pov = pov.drop(columns=['Unnamed: 1']).dropna()
pov = pov.rename(columns={'Taux de pauvreté': 'poverty_rate', 'Gouvernorat:': 'gouvernorat'})
pov['gouvernorat'] = pov['gouvernorat'].apply(lambda x: x.title())

In [130]:
pov.loc[len(pov)] = {'gouvernorat': 'Tunisie', 'poverty_rate': pov.poverty_rate.mean()}

In [131]:
pov

    gouvernorat  poverty_rate
1         Tunis      4.600000
3        Ariana      7.000000
5     Ben Arous      5.600000
7       Manouba      9.800000
9        Nabeul      8.100000
11     Zaghouan     13.700000
13      Bizerte     16.900000
15         Beja     26.400000
17     Jendouba     21.500000
19       Le Kef     33.100000
21      Siliana     24.700000
23       Sousse     14.300000
25     Monastir      7.700000
27       Mahdia     25.000000
29         Sfax      6.300000
31     Kairouan     29.300000
33    Kasserine     33.600000
35  Sidi Bouzid     25.000000
37        Gabes     16.900000
39      Mednine     18.500000
41    Tataouine     17.800000
43        Gafsa     19.000000
45       Tozeur     14.600000
47       Kebeli     19.200000
24      Tunisie     17.441667

In [106]:
population = pd.read_csv('app/geo/Data/population.csv')

In [133]:
pop_pov = pd.merge(
    population,
    pov,
    on='gouvernorat',
)

In [135]:
pop_pov.to_csv('app/geo/Data/population_poverty.csv', index=False)